// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzgreeiarabvyaqqxhpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6Z3JlZWlhcmFidnlhcXF4aHB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDgzMzQsImV4cCI6MjA2NTU4NDMzNH0.AhX8jwjka6ESRWhH6TiRJXFQgS8NmoYuRT5j57R_USc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);